/**
 * Metric Registry
 * Central authoritative source for all metric definitions
 * Used for tooltips and the Definitions modal
 */

import { MetricDefinition } from '../types'

export const metricRegistry: Record<string, MetricDefinition> = {
  // Revenue Metrics
  grossSales: {
    id: 'grossSales',
    label: 'Gross Sales',
    definition: 'Total revenue from all services and products before any deductions',
    formula: 'Sum of (service prices + product prices) for all completed appointments',
    exclusions: ['Cancelled appointments', 'No-shows', 'Gift card sales'],
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment', 'transaction'],
  },
  netSales: {
    id: 'netSales',
    label: 'Net Sales',
    definition: 'Revenue after discounts and refunds, excluding tax and tips',
    formula: 'Gross Sales - Discounts - Refunds',
    exclusions: ['Tax', 'Tips', 'Gift card redemptions'],
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment', 'transaction'],
  },
  totalCollected: {
    id: 'totalCollected',
    label: 'Total Collected',
    definition: 'Total amount received including tax and tips',
    formula: 'Net Sales + Tax + Tips',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  avgTicket: {
    id: 'avgTicket',
    label: 'Average Ticket',
    definition: 'Average revenue per completed appointment',
    formula: 'Net Sales / Number of Completed Appointments',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  discounts: {
    id: 'discounts',
    label: 'Discounts',
    definition: 'Total value of discounts applied',
    formula: 'Sum of all discount amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment', 'transaction'],
  },
  refunds: {
    id: 'refunds',
    label: 'Refunds',
    definition: 'Total amount refunded to customers',
    formula: 'Sum of all refund amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  
  // Profit Metrics
  contributionMargin: {
    id: 'contributionMargin',
    label: 'Contribution Margin $',
    definition: 'Net Sales minus direct costs (COGS, processing fees, direct labor)',
    formula: 'Net Sales - COGS - Processing Fees - Direct Labor',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment', 'transaction'],
  },
  contributionMarginPercent: {
    id: 'contributionMarginPercent',
    label: 'Contribution Margin %',
    definition: 'Contribution margin as a percentage of Net Sales',
    formula: '(Contribution Margin $ / Net Sales) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment', 'transaction'],
  },
  grossMarginPercent: {
    id: 'grossMarginPercent',
    label: 'Gross Margin %',
    definition: 'Gross profit margin before operating expenses',
    formula: '((Net Sales - COGS) / Net Sales) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  avgMarginPerAppt: {
    id: 'avgMarginPerAppt',
    label: 'Avg Margin/Appointment',
    definition: 'Average contribution margin per completed appointment',
    formula: 'Contribution Margin $ / Number of Completed Appointments',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  estimatedCOGS: {
    id: 'estimatedCOGS',
    label: 'Estimated COGS',
    definition: 'Estimated cost of goods sold including supplies used',
    formula: 'Sum of (estimated supply cost per service × appointments)',
    exclusions: ['Services without cost estimates'],
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment', 'inventory'],
  },
  processingFees: {
    id: 'processingFees',
    label: 'Processing Fees',
    definition: 'Credit card and payment processing fees',
    formula: 'Sum of all transaction processing fees',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  directLabor: {
    id: 'directLabor',
    label: 'Direct Labor',
    definition: 'Labor costs directly attributable to services rendered',
    formula: 'Sum of (hourly rate × hours) + commissions for completed appointments',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  
  // Appointment Metrics
  appointmentsCompleted: {
    id: 'appointmentsCompleted',
    label: 'Appointments Completed',
    definition: 'Number of appointments that were successfully completed',
    formula: 'Count of appointments with status = completed',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  appointmentsBooked: {
    id: 'appointmentsBooked',
    label: 'Appointments Booked',
    definition: 'Total number of appointments booked in the period',
    formula: 'Count of all appointments created',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  appointmentsCancelled: {
    id: 'appointmentsCancelled',
    label: 'Appointments Cancelled',
    definition: 'Number of appointments that were cancelled',
    formula: 'Count of appointments with status = cancelled',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  noShowRate: {
    id: 'noShowRate',
    label: 'No-Show Rate',
    definition: 'Percentage of scheduled appointments that were no-shows',
    formula: '(No-shows / (Completed + No-shows + Late Cancellations)) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  lateCancelRate: {
    id: 'lateCancelRate',
    label: 'Late Cancel Rate',
    definition: 'Percentage of appointments cancelled within 24 hours',
    formula: '(Late Cancellations / Total Bookings) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  lostRevenue: {
    id: 'lostRevenue',
    label: 'Lost Revenue',
    definition: 'Estimated revenue lost due to no-shows and late cancellations',
    formula: 'Sum of (average ticket × no-shows) + (average ticket × late cancellations)',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  recoveryRate: {
    id: 'recoveryRate',
    label: 'Recovery Rate',
    definition: 'Percentage of no-shows/cancellations that rebooked within 7 days',
    formula: '(Rebooked within 7 days / (No-shows + Cancellations)) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  avgLeadTime: {
    id: 'avgLeadTime',
    label: 'Avg Lead Time',
    definition: 'Average days between booking and appointment date',
    formula: 'Sum of (appointment date - booking date) / count',
    timeBasisSensitivity: true,
    format: 'days',
    drillRowTypes: ['appointment'],
  },
  utilizationPercent: {
    id: 'utilizationPercent',
    label: 'Utilization %',
    definition: 'Percentage of available capacity that was booked',
    formula: '(Booked Hours / Available Hours) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  
  // Retention Metrics
  rebook24h: {
    id: 'rebook24h',
    label: 'Rebook 0-24h',
    definition: 'Percentage of clients who rebooked within 24 hours of checkout',
    formula: '(Rebooked within 24h / Completed appointments) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment', 'client'],
  },
  rebook7d: {
    id: 'rebook7d',
    label: 'Rebook ≤7 Days',
    definition: 'Percentage of clients who rebooked within 7 days of checkout',
    formula: '(Rebooked within 7d / Completed appointments) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment', 'client'],
  },
  rebook30d: {
    id: 'rebook30d',
    label: 'Rebook ≤30 Days',
    definition: 'Percentage of clients who rebooked within 30 days of checkout',
    formula: '(Rebooked within 30d / Completed appointments) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment', 'client'],
  },
  avgDaysToNextVisit: {
    id: 'avgDaysToNextVisit',
    label: 'Avg Days to Next Visit',
    definition: 'Average number of days between visits for returning clients',
    formula: 'Sum of (days between consecutive visits) / count',
    timeBasisSensitivity: false,
    format: 'days',
    drillRowTypes: ['client'],
  },
  return90d: {
    id: 'return90d',
    label: '90-Day Return Rate',
    definition: 'Percentage of clients who returned within 90 days',
    formula: '(Clients with visit in last 90 days / Total active clients) × 100',
    timeBasisSensitivity: false,
    format: 'percent',
    drillRowTypes: ['client'],
  },
  
  // Client Metrics
  avgLTV12m: {
    id: 'avgLTV12m',
    label: 'Avg LTV (12 Months)',
    definition: 'Average lifetime value per client over 12 months',
    formula: 'Total revenue from clients in 12 months / Number of clients',
    timeBasisSensitivity: false,
    format: 'money',
    drillRowTypes: ['client'],
  },
  medianVisits12m: {
    id: 'medianVisits12m',
    label: 'Median Visits (12 Months)',
    definition: 'Median number of visits per client over 12 months',
    formula: 'Median of (visits per client in 12 months)',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['client'],
  },
  newClients: {
    id: 'newClients',
    label: 'New Clients',
    definition: 'Number of first-time clients in the period',
    formula: 'Count of clients with first visit in period',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['client'],
  },
  retention90d: {
    id: 'retention90d',
    label: 'Retention at 90 Days',
    definition: 'Percentage of clients retained at 90 days after first visit',
    formula: '(Clients with 2+ visits within 90 days of first / New clients) × 100',
    timeBasisSensitivity: false,
    format: 'percent',
    drillRowTypes: ['client'],
  },
  retention180d: {
    id: 'retention180d',
    label: 'Retention at 180 Days',
    definition: 'Percentage of clients retained at 180 days after first visit',
    formula: '(Clients with 2+ visits within 180 days of first / New clients) × 100',
    timeBasisSensitivity: false,
    format: 'percent',
    drillRowTypes: ['client'],
  },
  retention360d: {
    id: 'retention360d',
    label: 'Retention at 360 Days',
    definition: 'Percentage of clients retained at 360 days after first visit',
    formula: '(Clients with 2+ visits within 360 days of first / New clients) × 100',
    timeBasisSensitivity: false,
    format: 'percent',
    drillRowTypes: ['client'],
  },
  
  // Staff Metrics
  revenuePerHour: {
    id: 'revenuePerHour',
    label: 'Revenue/Hour',
    definition: 'Net sales generated per hour worked',
    formula: 'Net Sales / Hours Worked',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  marginPerHour: {
    id: 'marginPerHour',
    label: 'Margin/Hour',
    definition: 'Contribution margin generated per hour worked',
    formula: 'Contribution Margin $ / Hours Worked',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  upsellRate: {
    id: 'upsellRate',
    label: 'Upsell Rate',
    definition: 'Percentage of appointments with add-on services',
    formula: '(Appointments with add-ons / Total appointments) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  onTimeStartPercent: {
    id: 'onTimeStartPercent',
    label: 'On-Time Start %',
    definition: 'Percentage of appointments started within 5 minutes of scheduled time',
    formula: '(On-time starts / Total appointments) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  tipsPerHour: {
    id: 'tipsPerHour',
    label: 'Tips/Hour',
    definition: 'Tips received per hour worked',
    formula: 'Total Tips / Hours Worked',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  
  // Payroll Metrics
  totalPayout: {
    id: 'totalPayout',
    label: 'Total Payout',
    definition: 'Total compensation paid to all staff',
    formula: 'Commission + Hourly + Tips + Adjustments',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  commissionTotal: {
    id: 'commissionTotal',
    label: 'Commission Total',
    definition: 'Total commission earnings for all staff',
    formula: 'Sum of (service price × commission rate) for all completed services',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  hourlyTotal: {
    id: 'hourlyTotal',
    label: 'Hourly Total',
    definition: 'Total hourly wages paid',
    formula: 'Sum of (hourly rate × hours worked) for all staff',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  
  // Tips Metrics
  totalTips: {
    id: 'totalTips',
    label: 'Total Tips',
    definition: 'Total tips collected',
    formula: 'Sum of all tip amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment', 'transaction'],
  },
  avgTipPercent: {
    id: 'avgTipPercent',
    label: 'Avg Tip %',
    definition: 'Average tip as percentage of service total',
    formula: '(Total Tips / Net Sales) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  tipFeeCost: {
    id: 'tipFeeCost',
    label: 'Tip Fee Cost',
    definition: 'Processing fees charged on card tips',
    formula: 'Sum of (card tip amount × processing rate)',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  
  // Tax Metrics
  taxableSales: {
    id: 'taxableSales',
    label: 'Taxable Sales',
    definition: 'Total sales subject to tax',
    formula: 'Sum of taxable service and product amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  nonTaxableSales: {
    id: 'nonTaxableSales',
    label: 'Non-Taxable Sales',
    definition: 'Total sales exempt from tax',
    formula: 'Sum of non-taxable service and product amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  taxesCollected: {
    id: 'taxesCollected',
    label: 'Taxes Collected',
    definition: 'Total tax amount collected',
    formula: 'Sum of all tax amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  
  // Inventory Metrics
  itemsBelowReorder: {
    id: 'itemsBelowReorder',
    label: 'Items Below Reorder',
    definition: 'Number of inventory items below reorder level',
    formula: 'Count of items where quantity < reorder level',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['inventory'],
  },
  daysOfSupply: {
    id: 'daysOfSupply',
    label: 'Days of Supply',
    definition: 'Estimated days until inventory runs out at current usage rate',
    formula: 'Current quantity / average daily usage',
    timeBasisSensitivity: false,
    format: 'days',
    drillRowTypes: ['inventory'],
  },
  costUsed: {
    id: 'costUsed',
    label: 'Cost Used',
    definition: 'Total cost of inventory used in the period',
    formula: 'Sum of (units used × unit cost)',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['inventory'],
  },
  costPerAppt: {
    id: 'costPerAppt',
    label: 'Cost per Appointment',
    definition: 'Average inventory cost per appointment',
    formula: 'Cost Used / Completed Appointments',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['inventory', 'appointment'],
  },
  
  // Marketing Metrics
  messagesSent: {
    id: 'messagesSent',
    label: 'Messages Sent',
    definition: 'Total number of messages sent',
    formula: 'Count of all sent messages',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['message'],
  },
  confirmations: {
    id: 'confirmations',
    label: 'Confirmations',
    definition: 'Number of appointment confirmations received',
    formula: 'Count of messages where confirmed = true',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['message'],
  },
  showUpsAttributed: {
    id: 'showUpsAttributed',
    label: 'Show-ups Attributed',
    definition: 'Appointments completed attributed to marketing messages',
    formula: 'Count of completed appointments with attributed message within 7 days',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['message', 'appointment'],
  },
  costPerShowUp: {
    id: 'costPerShowUp',
    label: 'Cost per Show-up',
    definition: 'Marketing cost per attributed appointment',
    formula: 'Message cost / Show-ups attributed',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['message'],
  },
  marketingROI: {
    id: 'marketingROI',
    label: 'Marketing ROI',
    definition: 'Return on investment for marketing spend',
    formula: '(Attributed Revenue - Marketing Cost) / Marketing Cost',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['message', 'appointment'],
  },
  
  // Finance Metrics  
  pendingUnpaid: {
    id: 'pendingUnpaid',
    label: 'Pending/Unpaid',
    definition: 'Total amount of pending or unpaid invoices',
    formula: 'Sum of invoices with status = pending',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  netDeposits: {
    id: 'netDeposits',
    label: 'Net Deposits (Est)',
    definition: 'Estimated amount deposited to bank after fees',
    formula: 'Total Collected - Processing Fees - Refunds',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  
  // Additional Metrics for Reports
  totalRevenue: {
    id: 'totalRevenue',
    label: 'Total Revenue',
    definition: 'Total revenue from all completed appointments',
    formula: 'Sum of net revenue from all completed appointments',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment', 'transaction'],
  },
  totalAppointments: {
    id: 'totalAppointments',
    label: 'Total Appointments',
    definition: 'Number of appointments in the selected period',
    formula: 'Count of all appointments',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  addOnRevenue: {
    id: 'addOnRevenue',
    label: 'Add-On Revenue',
    definition: 'Total revenue from add-on services',
    formula: 'Sum of all add-on service prices',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  addOnCount: {
    id: 'addOnCount',
    label: 'Add-Ons Sold',
    definition: 'Total number of add-ons sold',
    formula: 'Count of add-on services sold',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  attachRate: {
    id: 'attachRate',
    label: 'Attach Rate',
    definition: 'Percentage of appointments with add-on services',
    formula: '(Appointments with add-ons / Total appointments) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  uniqueAddOns: {
    id: 'uniqueAddOns',
    label: 'Unique Add-Ons',
    definition: 'Number of different add-on services sold',
    formula: 'Count of distinct add-on types',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  uniqueServices: {
    id: 'uniqueServices',
    label: 'Unique Services',
    definition: 'Number of different services offered',
    formula: 'Count of distinct service types',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  avgServicePrice: {
    id: 'avgServicePrice',
    label: 'Avg Service Price',
    definition: 'Average price per service',
    formula: 'Total service revenue / Number of services sold',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  topServiceShare: {
    id: 'topServiceShare',
    label: 'Top Service Share',
    definition: 'Revenue share of the top performing service',
    formula: '(Top service revenue / Total service revenue) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  topServiceRevenue: {
    id: 'topServiceRevenue',
    label: 'Top Service Revenue',
    definition: 'Revenue from the highest performing service',
    formula: 'Revenue from top performing service',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  topServiceMargin: {
    id: 'topServiceMargin',
    label: 'Top Service Margin',
    definition: 'Profit margin of the top performing service',
    formula: '(Top service profit / Top service revenue) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  uniqueCombinations: {
    id: 'uniqueCombinations',
    label: 'Unique Combinations',
    definition: 'Number of unique breed/weight class combinations',
    formula: 'Count of distinct breed + weight class pairs',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  topComboCount: {
    id: 'topComboCount',
    label: 'Top Combo Count',
    definition: 'Count of appointments for the most popular combination',
    formula: 'Count of appointments for top breed/weight combo',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  totalClients: {
    id: 'totalClients',
    label: 'Total Clients',
    definition: 'Total number of unique clients',
    formula: 'Count of distinct clients',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['client'],
  },
  totalPets: {
    id: 'totalPets',
    label: 'Total Pets',
    definition: 'Total number of pets serviced',
    formula: 'Count of distinct pets',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  avgVisits: {
    id: 'avgVisits',
    label: 'Avg Visits',
    definition: 'Average number of visits per client',
    formula: 'Total appointments / Total clients',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['client'],
  },
  avgSpend: {
    id: 'avgSpend',
    label: 'Avg Spend',
    definition: 'Average spending per client',
    formula: 'Total revenue / Total clients',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['client'],
  },
  topClientSpend: {
    id: 'topClientSpend',
    label: 'Top Client Spend',
    definition: 'Spending by the highest value client',
    formula: 'Maximum client total spend',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['client'],
  },
  avgLTV: {
    id: 'avgLTV',
    label: 'Avg LTV',
    definition: 'Average lifetime value per client',
    formula: 'Average of all client lifetime values',
    timeBasisSensitivity: false,
    format: 'money',
    drillRowTypes: ['client'],
  },
  newCustomers: {
    id: 'newCustomers',
    label: 'New Customers',
    definition: 'Number of new customers in the period',
    formula: 'Count of clients with first visit in period',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['client'],
  },
  returningCustomers: {
    id: 'returningCustomers',
    label: 'Returning Customers',
    definition: 'Number of returning customers in the period',
    formula: 'Count of clients with previous visits',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['client'],
  },
  returningClients: {
    id: 'returningClients',
    label: 'Returning Clients',
    definition: 'Number of returning clients',
    formula: 'Count of clients with multiple visits',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['client'],
  },
  newRevenue: {
    id: 'newRevenue',
    label: 'New Customer Revenue',
    definition: 'Revenue from new customers',
    formula: 'Sum of revenue from first-time customers',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['client', 'appointment'],
  },
  returningRevenue: {
    id: 'returningRevenue',
    label: 'Returning Customer Revenue',
    definition: 'Revenue from returning customers',
    formula: 'Sum of revenue from repeat customers',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['client', 'appointment'],
  },
  retentionRate: {
    id: 'retentionRate',
    label: 'Retention Rate',
    definition: 'Percentage of clients retained over time',
    formula: '(Returning clients / Total clients) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['client'],
  },
  avgRebookRate: {
    id: 'avgRebookRate',
    label: 'Avg Rebook Rate',
    definition: 'Average rebooking rate across clients',
    formula: 'Average of all client rebook rates',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['client'],
  },
  avgDaysBetween: {
    id: 'avgDaysBetween',
    label: 'Avg Days Between',
    definition: 'Average days between client visits',
    formula: 'Sum of days between visits / Number of visit pairs',
    timeBasisSensitivity: false,
    format: 'days',
    drillRowTypes: ['client'],
  },
  avgRetentionDays: {
    id: 'avgRetentionDays',
    label: 'Avg Retention Days',
    definition: 'Average number of days clients stay active',
    formula: 'Average of (last visit - first visit) for all clients',
    timeBasisSensitivity: false,
    format: 'days',
    drillRowTypes: ['client'],
  },
  tipsTotal: {
    id: 'tipsTotal',
    label: 'Total Tips',
    definition: 'Total tips collected',
    formula: 'Sum of all tip amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment', 'transaction'],
  },
  avgTipPerAppt: {
    id: 'avgTipPerAppt',
    label: 'Avg Tip per Appt',
    definition: 'Average tip per appointment',
    formula: 'Total tips / Completed appointments',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  tipFees: {
    id: 'tipFees',
    label: 'Tip Processing Fees',
    definition: 'Processing fees charged on card tips',
    formula: 'Sum of (card tip × processing rate)',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  netToStaff: {
    id: 'netToStaff',
    label: 'Net to Staff',
    definition: 'Net tips paid to staff after processing fees',
    formula: 'Total Tips - Tip Processing Fees',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  totalDiscounts: {
    id: 'totalDiscounts',
    label: 'Total Discounts',
    definition: 'Total value of discounts applied',
    formula: 'Sum of all discount amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment', 'transaction'],
  },
  totalFees: {
    id: 'totalFees',
    label: 'Total Fees',
    definition: 'Total additional fees collected',
    formula: 'Sum of all additional fee amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment', 'transaction'],
  },
  avgDiscount: {
    id: 'avgDiscount',
    label: 'Avg Discount',
    definition: 'Average discount per appointment',
    formula: 'Total discounts / Discounted appointments',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  avgFee: {
    id: 'avgFee',
    label: 'Avg Fee',
    definition: 'Average additional fee per appointment',
    formula: 'Total fees / Appointments with fees',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  discountRate: {
    id: 'discountRate',
    label: 'Discount Rate',
    definition: 'Percentage of appointments with discounts',
    formula: '(Discounted appointments / Total appointments) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  appointmentsWithDiscount: {
    id: 'appointmentsWithDiscount',
    label: 'Appts with Discounts',
    definition: 'Number of appointments with discounts applied',
    formula: 'Count of appointments with discounts > 0',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  appointmentsWithFees: {
    id: 'appointmentsWithFees',
    label: 'Appts with Fees',
    definition: 'Number of appointments with additional fees',
    formula: 'Count of appointments with fees > 0',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  groomersWithDiscounts: {
    id: 'groomersWithDiscounts',
    label: 'Groomers with Discounts',
    definition: 'Number of groomers who applied discounts',
    formula: 'Count of distinct groomers with discount appointments',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  topDiscounter: {
    id: 'topDiscounter',
    label: 'Top Discounter',
    definition: 'Total discounts by the groomer who applied most discounts',
    formula: 'Maximum groomer discount total',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  topFeeCollector: {
    id: 'topFeeCollector',
    label: 'Top Fee Collector',
    definition: 'Total fees collected by the top fee-collecting groomer',
    formula: 'Maximum groomer fee total',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  grossProfit: {
    id: 'grossProfit',
    label: 'Gross Profit',
    definition: 'Revenue minus cost of goods sold',
    formula: 'Net Sales - COGS',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment', 'transaction'],
  },
  avgMargin: {
    id: 'avgMargin',
    label: 'Avg Margin',
    definition: 'Average profit margin percentage',
    formula: '(Gross Profit / Net Sales) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  laborCost: {
    id: 'laborCost',
    label: 'Labor Cost',
    definition: 'Total labor costs',
    formula: 'Sum of all labor expenses',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  suppliesCost: {
    id: 'suppliesCost',
    label: 'Supplies Cost',
    definition: 'Total cost of supplies used',
    formula: 'Sum of all supplies expenses',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['inventory'],
  },
  taxCollected: {
    id: 'taxCollected',
    label: 'Tax Collected',
    definition: 'Total tax amount collected',
    formula: 'Sum of all tax amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  totalRefunds: {
    id: 'totalRefunds',
    label: 'Total Refunds',
    definition: 'Total amount refunded',
    formula: 'Sum of all refund amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  cardRevenue: {
    id: 'cardRevenue',
    label: 'Card Revenue',
    definition: 'Revenue from card payments',
    formula: 'Sum of card transaction amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  cashRevenue: {
    id: 'cashRevenue',
    label: 'Cash Revenue',
    definition: 'Revenue from cash payments',
    formula: 'Sum of cash transaction amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  avgDuration: {
    id: 'avgDuration',
    label: 'Avg Duration',
    definition: 'Average appointment duration',
    formula: 'Sum of appointment durations / Count of appointments',
    timeBasisSensitivity: true,
    format: 'minutes',
    drillRowTypes: ['appointment'],
  },
  avgDurationVariance: {
    id: 'avgDurationVariance',
    label: 'Avg Duration Variance',
    definition: 'Average difference between scheduled and actual duration',
    formula: 'Avg of (actual duration - scheduled duration)',
    timeBasisSensitivity: true,
    format: 'minutes',
    drillRowTypes: ['appointment'],
  },
  totalHours: {
    id: 'totalHours',
    label: 'Total Hours',
    definition: 'Total grooming hours',
    formula: 'Sum of all appointment durations / 60',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  avgRevenuePerHour: {
    id: 'avgRevenuePerHour',
    label: 'Avg Revenue/Hour',
    definition: 'Average revenue per grooming hour',
    formula: 'Total revenue / Total hours',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  bookedAppointments: {
    id: 'bookedAppointments',
    label: 'Booked Appts',
    definition: 'Number of booked appointments',
    formula: 'Count of appointments with status = booked',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  cancelledAppointments: {
    id: 'cancelledAppointments',
    label: 'Cancelled Appts',
    definition: 'Number of cancelled appointments',
    formula: 'Count of appointments with status = cancelled',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  uniqueBreeds: {
    id: 'uniqueBreeds',
    label: 'Unique Breeds',
    definition: 'Number of different breeds serviced',
    formula: 'Count of distinct breeds',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  uniqueWeightClasses: {
    id: 'uniqueWeightClasses',
    label: 'Weight Classes',
    definition: 'Number of weight classes serviced',
    formula: 'Count of distinct weight classes',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  topBreedRevenue: {
    id: 'topBreedRevenue',
    label: 'Top Breed Revenue',
    definition: 'Revenue from the highest performing breed',
    formula: 'Revenue from top performing breed',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  topBreedCount: {
    id: 'topBreedCount',
    label: 'Top Breed Count',
    definition: 'Appointment count for the most popular breed',
    formula: 'Count of appointments for top breed',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  topBreedShare: {
    id: 'topBreedShare',
    label: 'Top Breed Share',
    definition: 'Revenue share of the top performing breed',
    formula: '(Top breed revenue / Total revenue) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  topBreedLTV: {
    id: 'topBreedLTV',
    label: 'Top Breed LTV',
    definition: 'Lifetime value of the top breed',
    formula: 'Average LTV for top breed clients',
    timeBasisSensitivity: false,
    format: 'money',
    drillRowTypes: ['client'],
  },
  topClassCount: {
    id: 'topClassCount',
    label: 'Top Class Count',
    definition: 'Appointment count for the most popular weight class',
    formula: 'Count of appointments for top weight class',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  topClassShare: {
    id: 'topClassShare',
    label: 'Top Class Share',
    definition: 'Revenue share of the top weight class',
    formula: '(Top weight class revenue / Total revenue) × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  referralSources: {
    id: 'referralSources',
    label: 'Referral Sources',
    definition: 'Number of different referral sources',
    formula: 'Count of distinct referral sources',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['client'],
  },
  topSourceCount: {
    id: 'topSourceCount',
    label: 'Top Source Count',
    definition: 'Client count from top referral source',
    formula: 'Count of clients from top referral source',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['client'],
  },
  uniqueProducts: {
    id: 'uniqueProducts',
    label: 'Unique Products',
    definition: 'Number of different retail products sold',
    formula: 'Count of distinct products sold',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['inventory'],
  },
  unitsSold: {
    id: 'unitsSold',
    label: 'Units Sold',
    definition: 'Total number of retail units sold',
    formula: 'Sum of all product quantities sold',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['inventory'],
  },
  retailRevenue: {
    id: 'retailRevenue',
    label: 'Retail Revenue',
    definition: 'Revenue from retail product sales',
    formula: 'Sum of retail product sales',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['inventory', 'transaction'],
  },
  totalRetail: {
    id: 'totalRetail',
    label: 'Total Retail',
    definition: 'Total retail sales amount',
    formula: 'Sum of all retail transactions',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['inventory', 'transaction'],
  },
  totalService: {
    id: 'totalService',
    label: 'Total Service',
    definition: 'Total service revenue',
    formula: 'Sum of all service revenue',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  totalServices: {
    id: 'totalServices',
    label: 'Total Services',
    definition: 'Number of services performed',
    formula: 'Count of all services rendered',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  totalVisits: {
    id: 'totalVisits',
    label: 'Total Visits',
    definition: 'Total number of client visits',
    formula: 'Count of all completed appointments',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  totalSpend: {
    id: 'totalSpend',
    label: 'Total Spend',
    definition: 'Total client spending',
    formula: 'Sum of all transaction amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  totalCollectedTxn: {
    id: 'totalCollectedTxn',
    label: 'Total Collected',
    definition: 'Total amount collected from transactions',
    formula: 'Sum of all payment amounts',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  avgPerAppt: {
    id: 'avgPerAppt',
    label: 'Avg per Appointment',
    definition: 'Average amount per appointment',
    formula: 'Total amount / Number of appointments',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  avgMonthly: {
    id: 'avgMonthly',
    label: 'Avg Monthly',
    definition: 'Average monthly value',
    formula: 'Total value / Number of months',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  avgVisitsPerYear: {
    id: 'avgVisitsPerYear',
    label: 'Avg Visits/Year',
    definition: 'Average visits per client per year',
    formula: 'Total visits / Clients / Years',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['client'],
  },
  netSalesExTaxTips: {
    id: 'netSalesExTaxTips',
    label: 'Net Sales (ex Tax/Tips)',
    definition: 'Net sales excluding tax and tips',
    formula: 'Total Collected - Tax - Tips',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  staffAvgTicket: {
    id: 'staffAvgTicket',
    label: 'Staff Avg Ticket',
    definition: 'Average ticket value per staff member',
    formula: 'Total revenue / Staff members',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  staffRebookRate: {
    id: 'staffRebookRate',
    label: 'Staff Rebook Rate',
    definition: 'Average rebooking rate per staff member',
    formula: 'Average of staff rebook rates',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
  adjustmentsTotal: {
    id: 'adjustmentsTotal',
    label: 'Adjustments Total',
    definition: 'Total payroll adjustments',
    formula: 'Sum of all payroll adjustments',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  appointments: {
    id: 'appointments',
    label: 'Appointments',
    definition: 'Number of appointments',
    formula: 'Count of appointments',
    timeBasisSensitivity: true,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  weightClasses: {
    id: 'weightClasses',
    label: 'Weight Classes',
    definition: 'Number of weight class categories',
    formula: 'Count of distinct weight classes',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  uniqueCombos: {
    id: 'uniqueCombos',
    label: 'Unique Combos',
    definition: 'Number of unique service combinations',
    formula: 'Count of distinct service combinations',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  uniqueGroups: {
    id: 'uniqueGroups',
    label: 'Unique Groups',
    definition: 'Number of unique groupings',
    formula: 'Count of distinct groups',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['appointment'],
  },
  currentMonth: {
    id: 'currentMonth',
    label: 'Current Month',
    definition: 'Value for current month',
    formula: 'Sum of values in current month',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['transaction'],
  },
  paymentMethods: {
    id: 'paymentMethods',
    label: 'Payment Methods',
    definition: 'Number of payment methods used',
    formula: 'Count of distinct payment methods',
    timeBasisSensitivity: false,
    format: 'number',
    drillRowTypes: ['transaction'],
  },
  bestPerforming: {
    id: 'bestPerforming',
    label: 'Best Performing',
    definition: 'Value of best performing item',
    formula: 'Maximum value in category',
    timeBasisSensitivity: true,
    format: 'money',
    drillRowTypes: ['appointment'],
  },
  fastestAvg: {
    id: 'fastestAvg',
    label: 'Fastest Avg',
    definition: 'Fastest average duration',
    formula: 'Minimum average duration',
    timeBasisSensitivity: true,
    format: 'minutes',
    drillRowTypes: ['appointment'],
  },
  slowestAvg: {
    id: 'slowestAvg',
    label: 'Slowest Avg',
    definition: 'Slowest average duration',
    formula: 'Maximum average duration',
    timeBasisSensitivity: true,
    format: 'minutes',
    drillRowTypes: ['appointment'],
  },
  attachUpsellRate: {
    id: 'attachUpsellRate',
    label: 'Attach/Upsell Rate',
    definition: 'Combined attachment and upsell rate',
    formula: '(Add-ons + Upsells) / Appointments × 100',
    timeBasisSensitivity: true,
    format: 'percent',
    drillRowTypes: ['appointment'],
  },
}

/**
 * Get metric definition by ID
 */
export function getMetricDefinition(metricId: string): MetricDefinition | undefined {
  return metricRegistry[metricId]
}

/**
 * Get all metric definitions for a specific drill row type
 */
export function getMetricsByDrillType(drillType: 'appointment' | 'transaction' | 'client' | 'inventory' | 'message'): MetricDefinition[] {
  return Object.values(metricRegistry).filter(m => m.drillRowTypes.includes(drillType))
}

/**
 * Get all metrics sensitive to time basis changes
 */
export function getTimeSensitiveMetrics(): MetricDefinition[] {
  return Object.values(metricRegistry).filter(m => m.timeBasisSensitivity)
}

/**
 * Format metric value for display
 */
export function formatMetricValue(value: number, format: MetricDefinition['format']): string {
  switch (format) {
    case 'money':
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0,
      }).format(value / 100) // Convert from cents
    case 'percent':
      return `${value.toFixed(1)}%`
    case 'number':
      return new Intl.NumberFormat('en-US').format(value)
    case 'minutes':
      return `${value.toFixed(0)} min`
    case 'days':
      return `${value.toFixed(1)} days`
    default:
      return String(value)
  }
}

/**
 * Format delta value with sign
 */
export function formatDelta(delta: number, format: MetricDefinition['format']): string {
  const sign = delta >= 0 ? '+' : ''
  switch (format) {
    case 'money':
      return `${sign}${new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0,
      }).format(delta / 100)}`
    case 'percent':
      return `${sign}${delta.toFixed(1)}%`
    case 'number':
      return `${sign}${new Intl.NumberFormat('en-US').format(delta)}`
    case 'minutes':
      return `${sign}${delta.toFixed(0)} min`
    case 'days':
      return `${sign}${delta.toFixed(1)} days`
    default:
      return `${sign}${delta}`
  }
}
